Add a part about Oh My ZSH themes libraries
z-shell/zw pull request #511
Opened 2022-05-27 17:22 UTC by signed-log

OMZ themes need their support libraries to function.

Add a note about them

Fixes #508

2022-05-27 20:24 UTC, ss-o requested changes

2022-05-28 03:48 UTC, signed-log commented on docs/getting_started/03_migration.md
> +:::tip
I think that is better to leave that out entirely actually

2022-05-28 04:31 UTC, ss-o requested changes

2022-05-28 04:31 UTC, ss-o commented on docs/getting_started/03_migration.md
> +- If you encounter an error message similar to :
You missed one :see_no_evil: 

About the rest is all fine by me. :100:

2022-05-28 04:38 UTC, ss-o commented on docs/getting_started/03_migration.md
> +:::tip
It's up to you :+1:

I just propose my opinion and it's totally up to the community to shape it as they are the ones who will use it :octocat:

2022-05-28 04:48 UTC, ss-o approved these changes
Most important all the docs are up to date and follow rules to be compatible, the rest can be easy adjusted with various tools :octocat: :+1:

2022-05-28 04:51 UTC, ss-o commented
Looks legit, thanks for taking the time :1st_place_medal:

2022-05-28 04:51 UTC, merged